TRUNCATE TABLE sks
TRUNCATE TABLE skmb
TRUNCATE TABLE trans_skbs
TRUNCATE TABLE trans_obat
TRUNCATE TABLE trans_obat_racikan
TRUNCATE TABLE trans_visit
TRUNCATE TABLE ms_patient
TRUNCATE TABLE trans_anamnesa
TRUNCATE TABLE trans_diagnosa
TRUNCATE TABLE trans_medical_record
